# check this file on https://config.travis-ci.com/explore

os: linux

dist: xenial

language: python

python:
    #- "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

env:
    - OPENCV_VERSION=">=3.4.0,<3.5.0"
    - OPENCV_VERSION=">=3.4.0,<4.0.0"
    - OPENCV_VERSION=">=4.0.0,<5.0.0"

install:
    - pip3 install "opencv-python$OPENCV_VERSION"

script:
    - "./scripts/run.sh"

